name: GSC Full Fetch to BigQuery (rev1)

on:
  schedule:
    # GitHub Actions uses UTC → 22:30 UTC = 02:00 Tehran time
    - cron: '30 22 * * *'
  workflow_dispatch:
    inputs:
      start_date:
        description: 'Start date (YYYY-MM-DD)'
        required: true
        default: '2024-08-01'
      end_date:
        description: 'End date (YYYY-MM-DD)'
        required: true
        default: '2025-09-30'
      debug:
        description: 'Enable debug mode'
        required: false
        default: 'false'

jobs:
  fullfetch-gsc-to-bq:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client google-cloud-bigquery tqdm pandas pyarrow db-dtypes pandas_gbq

      - name: Write GCP credentials file
        run: |
          if [ -n "${{ secrets.GHANADBASHI_GCP_SA_KEY_BASE64 }}" ]; then
            printf "%s" "${{ secrets.GHANADBASHI_GCP_SA_KEY_BASE64 }}" | base64 --decode > gcp-key.json
          elif [ -n "${{ secrets.GHANADBASHI_GCP_SA_KEY }}" ]; then
            printf "%s" "${{ secrets.GHANADBASHI_GCP_SA_KEY }}" > gcp-key.json
          else
            echo "❌ ERROR: Missing GCP credentials secret."
            exit 1
          fi

      - name: Validate gcp-key.json
        run: python -c "import json; json.load(open('gcp-key.json'))"

      - name: Run Full Fetch Python
        env:
          GOOGLE_APPLICATION_CREDENTIALS: gcp-key.json
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "schedule" ]; then
            # Compute last 7-day period (week ending yesterday)
            END_DATE=$(date -u -d "yesterday" +"%Y-%m-%d")
            START_DATE=$(date -u -d "$END_DATE -6 days" +"%Y-%m-%d")
            DEBUG_FLAG=""
          else
            # Manual run (workflow_dispatch)
            if [ "${{ github.event.inputs.debug }}" = "true" ]; then
              DEBUG_FLAG="--debug"
            else
              DEBUG_FLAG=""
            fi
            START_DATE="${{ github.event.inputs.start_date }}"
            END_DATE="${{ github.event.inputs.end_date }}"
          fi

          echo "📅 Fetching from $START_DATE to $END_DATE"

          CSV_TEST_FILE="gsc_fullfetch_test_rev02_${{ github.run_id }}.csv"

          python gsc_to_bq_fullfetch.py \
            $DEBUG_FLAG \
            --start-date "$START_DATE" \
            --end-date "$END_DATE" \
